celestiaorg/celestia-specs

specs/data_structures.md

Spec out crypto primitives

---

specs/data_structures.md

Link directly to SO answer instead of question.

Fix link to citation for low-probability of X being low for signatures

---

specs/data_structures.md

Explicitly specify enums as unsigned 8-bit (i.e. 1-byte) ints.

Specify enum sizes

---

specs/data_structures.md

consistency: `intermediateStateRoots` are `HashDigest[]` not `HashDigest`

Small fix: intermediateStateRoots are HashDigest[]

---

specs/data_structures.md

When hashing leaves for the SMT, also hash over the key of the leaf so that the key of each leaf is committed to.

Add key to leaf hash for SMT

---

specs/consensus.md

From incorrect `uint64` to fixed-size byte array.

Fix namespace ID type

---

specs/data_structures.md

Remove dependence on protobuf for core data structures. [TAI64](http://cr.yp.to/libtai/tai64.html) is chosen as the time format both because it's reasonable (unsigned 64 bit integer) and because it's the same format used by [Veriform](https://github.com/iqlusioninc/veriform).

Change protobuf timestamps to TAI64 timestamps

---

specs/data_structures.md

- Add namespace ID field to share data structure.
- Add note on serialization of shares to only use raw data.
Note: I intentionally did not fix the conflicting use of "message" for NMTs. That'll be handled in #41.
Rendered:
- https://github.com/lazyledger/lazyledger-specs/blob/adlerjohn-share_namespace/specs/data_structures.md

Add share namespace ID field

---

specs/data_structures.md

Add a new type of tx, `Burn`, which burns some coins. This can be used for one-way bridges (e.g. burning coins then minting them in a LazyLedger app). The burn tx includes a graffiti field to specify the burn reason.
Rendered:
- https://github.com/lazyledger/lazyledger-specs/blob/adlerjohn-burn_tx/specs/data_structures.md

Add new burn tx type

---

specs/data_structures.md

Rendered:
- https://github.com/lazyledger/lazyledger-specs/blob/adlerjohn-merkle_tree_fixes/specs/data_structures.md

Merkle tree misc fixes

---

specs/data_structures.md

Use hash of empty string for base case for Merkle trees

---

specs/data_structures.md

Ignore the namespace ID for siblings in the NMT if the sibling is the root of only parity shares, unless both siblings are that.

Ignore namespace ID for parity shares

---

specs/consensus.md
specs/data_structures.md

- Reduce size of namespace ID to 8 bytes, from 32 ([rationale](https://github.com/lazyledger/lazyledger-specs/issues/62#issuecomment-692894278))
- Unlink graffiti from namespace ID type definition

Reduce namespace ID size to 8 bytes, from 32

---

specs/data_structures.md

Closes https://github.com/lazyledger/lazyledger-specs/issues/63
Based on section 5.5 in https://arxiv.org/pdf/1809.09044.pdf.
rendered: https://github.com/lazyledger/lazyledger-specs/blob/rsmt2d-fraudproof/specs/data_structures.md#invalid-erasure-coding

Add erasure code fraud proof specification

---

specs/data_structures.md

Remove spaces from Merkle proof data structure names

---

rationale/message_block_layout.md
specs/consensus.md
specs/data_structures.md

And remove special tx to pay for padding.

Use previous message namespace ID for padding shares

---

specs/data_structures.md

Fixes #109.
Instead of serializing child nodes (which would require the use of a single serialization scheme but introduce a dependency on a serialization library to the trees), just use the raw bytes (which is technically a different serialization scheme but requires no library).

Use raw data for Merkle tree inner nodes instead of serialization

---

README.md
rationale/distributing_rewards.md
specs/node_types.md

Fixes #22.
Define different node types as a function of some configuration parameters (different levels of resource requirements for block headers, block bodies, and transactions).

Define node types and configuration parameters

---

rationale/distributing_rewards.md
specs/consensus.md
specs/data_structures.md

Fixes #95, #104.
Major changes:
* Remove `stakedBalance` for validators. Validators now have no balance and need to delegate to themselves. This can be abstracted away at the UI layer.
* Delegation commission is computed and rewards (both block subsidy and fees) are dispersed to both validators and delegations. Commission rewards are stored in a new field in the validator object.
Currently validator commission rewards simply sit there until the validator unbonds. We should support delegating this reward #117.

Add delegation rewards and commission

---

specs/consensus.md
specs/data_structures.md

Fixes #117.
* Tangential: Fix block reward to be distributed based on voting power at beginning of block, not end.
* Add two new tx types to "redelegate" pending rewards (for delegations) and pending commission rewards (for validators). Relegating requires moving all pending coins and computes new F1 entries since voting power changes.

Support delegation of commission and rewards without withdrawals

---

specs/data_structures.md

#114 missed removing the `amount` from `SignedTransactionDataCreateValidator`.

Remove amount field from create validator tx

---

specs/networking.md
specs/proto/wire.proto

Add explanation for the networking logic of `PayForMessage` transaction types.

Add PayForMessage networking rationale

---

specs/consensus.md

When the voting power is 0, just return 0 as the entry. This may happen if all a validator's delegations undelegate, leaving them with 0 voting power.

Handle divide-by-zero when computing new latest entries

---

specs/consensus.md
specs/data_structures.md

Fixes #120.
Defines the Decimal non-integer type as a rational number.

Define non-integer type

---

specs/consensus.md
specs/data_structures.md
specs/figures/block_data_structures.dot
specs/figures/block_data_structures.svg
specs/proto/consensus.proto

Fixes #126.
- Define _proposals_ and _votes_.
- Rename block ID to header hash, and hash header instead of Merkleizing it ([ref](https://github.com/tendermint/spec/issues/175#issuecomment-701543731)).

Define consensus messages

---

specs/figures/block_data_structures.dot
specs/proto/consensus.proto

- Fix name of `lastHeaderHash` in data structs figure
- Fix `CommitFlagAbsentNone` -> `CommitFlagNone` in proto

Minor fixes

---

.github/workflows/markdown_link_checker.yml

Set markdown link check action to run on pushes to master (and pushes to tags) and pull request updates, instead of any push (including to PR branches). This prevents the action from running twice in a PR.
(You can see redundant running of duplicate action [here](https://github.com/lazyledger/lazyledger-specs/pull/138/commits/2f679a0bc3f8a87473a12999b66d9347cec1384e))

Make GitHub action run on push or PR update, exclusive

---

specs/data_structures.md

Similar to transactions, prepend the length to messages too. This allows splitting the block into messages without actually parsing transactions (i.e. it saves ABCI calls in the implementation).

Prepend length to messages too

---

specs/data_structures.md

This reversion was missed here https://github.com/lazyledger/lazyledger-specs/commit/6d9648a454bcbfef79172152a4f129253cb7962d#diff-1da55b51e3377610ee9d688350d2e78dce2378036f534f67d63e873229e16f5a

Fix non-interactive empty share message NID requirement

---

specs/proto/consensus.proto

Fixes #153 and #154.
This adds the `POLRound` field to consensus proposals. It also refactors [proposals](https://github.com/lazyledger/lazyledger-core/blob/66dd73241e508bc439679afd49683282f8d47b5c/proto/tendermint/types/types.proto#L188-L198) and [votes](https://github.com/lazyledger/lazyledger-core/blob/66dd73241e508bc439679afd49683282f8d47b5c/proto/tendermint/types/types.proto#L155-L168) to conform to the implementation.
~~One difference between the implementation and this PR is the removal of the `available_data_header` field from proposals: https://github.com/lazyledger/lazyledger-specs/compare/adlerjohn/polround?expand=1#diff-48a78bd7e15d8c7211897da188db99d6576a27e125cbde564ae0238ae66e9e94L34~~
~~While the implementation [currently](https://github.com/lazyledger/lazyledger-core/blob/ …

Add Proof of Lock round to proposal struct

---

specs/networking.md
specs/proto/consensus.proto
specs/proto/types.proto

Fixes #163.
This optimization reduces the number of network round trips by putting both the header and DA header directly into the proposal, so that a single network message is needed to get everything except the block body.
Note that canonicalization is explicitly not addressed here, but will be in #94. Properly abstracted, canonicalization should only affect signature verification and initial network handshake, so _should_ be unimportant for processing.

Move header and DA header into proposal

---

.github/workflows/gh-pages.yml

Follow up on #165. This action will automatically deploy `master` to `https://lazyledger.github.io/lazyledger-specs/latest` and tags to `https://lazyledger.github.io/lazyledger-specs/<tag>`. (Unfortunately no good way to preview the effects of this action until it runs.)

Add CI action to deploy book to GitHub pages

---

.github/workflows/gh-pages.yml

Fix pages action to use `.` instead of `docs` 😬
https://github.com/lazyledger/lazyledger-specs/pull/167#issuecomment-850887306

Fix pages deploy action

---

src/rationale/distributing_rewards.md

Fix no space before underscore for italics.

Fix typo in rationale doc

---

src/specs/node_types.md

Ref: #175.
Note that storage nodes were already defined at the bottom: https://github.com/lazyledger/lazyledger-specs/blob/de7abfcbed571d5980b25c9ea2b182d141270232/src/specs/node_types.md#node-type-definitions
> Storage nodes provide the same security guarantees as full nodes. Block bodies (in erasure-coded form) are stored and served to the network. 
Expand node type descriptions.
Rendered: https://github.com/lazyledger/lazyledger-specs/blob/adlerjohn/expand_storage_nodes/src/specs/node_types.md#node-type-definitions

Note that partial nodes can act as storage nodes for subset of blocks

---

src/specs/data_structures.md

Namespaced Merkle Tree leaf node was changed to hash Namespace ID in the specs.

Change NMT Leaf Node to Hash the NID

---

README.md

The previous link redirects to https://github.com/celestiaorg/celestia-app but I think this change will reduce confusion

Update link to celestia-app
